/*
mailheaderclean_headers.h - Shared header removal list

This file contains the hardcoded list of non-essential email headers
to be removed by mailheaderclean. It is shared between the standalone
binary (mailheaderclean.c) and the bash loadable builtin (mailheaderclean_loadable.c).

To modify the removal list, edit this file only - both implementations
will automatically use the updated list.
*/

#ifndef MAILHEADERCLEAN_HEADERS_H
#define MAILHEADERCLEAN_HEADERS_H

/* Hardcoded list of headers to remove */
static const char *HEADERS_TO_REMOVE[] = {
    /* Microsoft Exchange / Office365 bloat */
    "x-ms-exchange-antispam-messagedata-0",
    "x-ms-exchange-antispam-messagedata-chunkcount",
    "x-ms-exchange-antispam-relay",
    "X-MS-Exchange-AntiSpam-ExternalHop-MessageData-0",
    "X-MS-Exchange-AntiSpam-ExternalHop-MessageData-ChunkCount",
    "X-MS-Exchange-AtpMessageProperties",
    "X-MS-Exchange-Authentication-Results",
    "X-MS-Exchange-CrossTenant-AuthAs",
    "X-MS-Exchange-CrossTenant-AuthSource",
    "X-MS-Exchange-CrossTenant-fromentityheader",
    "X-MS-Exchange-CrossTenant-id",
    "X-MS-Exchange-CrossTenant-mailboxtype",
    "X-MS-Exchange-CrossTenant-Network-Message-Id",
    "X-MS-Exchange-CrossTenant-originalarrivaltime",
    "X-MS-Exchange-CrossTenant-OriginalAttributedTenantConnectingIp",
    "X-MS-Exchange-CrossTenant-RMS-PersistedConsumerOrg",
    "X-MS-Exchange-CrossTenant-userprincipalname",
    "X-MS-Exchange-Generated-Message-Source",
    "X-MS-Exchange-Inbox-Rules-Loop",
    "X-MS-Exchange-MessageSentRepresentingType",
    "X-MS-Exchange-Organization-RecordReviewCfmType",
    "X-MS-Exchange-Organization-SCL",
    "X-MS-Exchange-Parent-Message-Id",
    "x-ms-exchange-senderadcheck",
    "X-MS-Exchange-SLBlob-MailProps",
    "X-MS-Exchange-Transport-CrossTenantHeadersStamped",
    "X-MS-Exchange-Transport-CrossTenantHeadersStripped",
    "X-MS-Has-Attach",
    "x-ms-office365-filtering-correlation-id",
    "X-MS-Office365-Filtering-Correlation-Id-Prvs",
    "x-ms-publictraffictype",
    "X-MS-Reactions",
    "X-MS-TNEF-Correlator",
    "x-ms-traffictypediagnostic",
    "x-microsoft-antispam",
    "x-microsoft-antispam-message-info",
    "X-Microsoft-Antispam-Message-Info-Original",
    "X-Microsoft-Antispam-Untrusted",
    "x-forefront-antispam-report",
    "X-Forefront-Antispam-Report-Untrusted",
    "X-ClientProxiedBy",
    "X-EOPAttributedMessage",
    "msip_labels",
    "Thread-Index",
    "Thread-Topic",
    "Deferred-Delivery",
    /* ARC email forwarding validation */
    "ARC-Authentication-Results",
    "ARC-Message-Signature",
    "ARC-Seal",
    "authentication-results",
    "Authentication-Results-Original",
    "auto-submitted",
    /* Organization tracking */
    "X-OriginatorOrg",
    /* Client preferences */
    "Accept-Language",
    "Content-Language",
    /* Email client/software identification */
    "X-Mailer",
    "User-Agent",
    "X-Mailer-Version",
    "X-MimeOLE",
    "X-MSMail-Priority",
    /* Priority/importance */
    "X-Priority",
    "Importance",
    "Priority",
    "Precedence",
    /* Tracking/receipts */
    "Disposition-Notification-To",
    "X-Confirm-Reading-To",
    "Return-Receipt-To",
    "X-Auto-Response-Suppress",
    /* Proofpoint */
    "X-Proofpoint-Virus-Version",
    "X-Proofpoint-Spam-Details",
    "X-Proofpoint-GUID",
    "X-Proofpoint-ORIG-GUID",
    /* Mimecast */
    "X-Mimecast-Spam-Score",
    "X-Mimecast-Bulk-Signature",
    "X-Mimecast-Spam-Signature",
    "X-Mimecast-Impersonation-Protect",
    /* IronPort */
    "X-IronPort-AV",
    "X-IronPort-Anti-Spam-Filtered",
    "X-IronPort-Anti-Spam-Result",
    /* Barracuda */
    "X-Barracuda-Spam-Score",
    "X-Barracuda-Spam-Status",
    "X-Barracuda-Spam-Report",
    "X-Barracuda-Virus-Scanned",
    /* Other security vendors */
    "X-FireEye",
    "X-Sophos-BARC",
    "X-Sophos-SAVI",
    "X-Sophos-Email",
    "X-Sophos-Email-ID",
    "X-Sophos-Mailflow-Processing-Id",
    "X-Sophos-Mf-Email-Transport-Route",
    "X-Sophos-MH-Mail-Info-Key",
    "X-Sophos-Product-Type",
    "X-TM-AS-Product-Ver",
    "X-TM-AS-Result",
    "X-SONIC-DKIM-SIGN",
    "X-Sonic-ID",
    "X-Sonic-MF",
    /* Amavis antivirus */
    "X-Amavis-Modified",
    "X-AntiAbuse",
    "X-Antivirus",
    "X-Antivirus-Status",
    "X-Virus-Scanned",
    /* LASED spam filter */
    "X-LASED-From-ReplyTo-Diff",
    "X-LASED-Hits",
    "X-LASED-Impersonation",
    "X-LASED-MailType",
    "X-LASED-Spam",
    "X-LASED-SpamProbability",
    /* Spampanel */
    "X-Spampanel-Domain",
    "X-Spampanel-Outgoing-Class",
    "X-Spampanel-Outgoing-Evidence",
    "X-Spampanel-Username",
    /* MailScanner */
    "X-YourOrg-MailScanner",
    "X-YourOrg-MailScanner-From",
    "X-YourOrg-MailScanner-ID",
    "X-YourOrg-MailScanner-Information",
    "X-YourOrg-MailScanner-SpamCheck",
    /* Google specific */
    "X-Google-DKIM-Signature",
    "X-Gm-Message-State",
    "X-Gm-Features",
    "X-Gm-Gg",
    "X-Google-Smtp-Source",
    "X-Google-Id",
    "X-GoogleForms-CustomerDisplayName",
    "X-GoogleForms-FormId",
    /* Yahoo specific */
    "X-Yahoo-Newman-Id",
    "X-Yahoo-Newman-Property",
    "X-YMail-OSG",
    "X-YMail-JAS",
    /* AOL specific */
    "X-AOL-IP",
    "X-AOL-SCOLL-SCORE",
    /* Mailing list headers */
    "List-Id",
    "List-Unsubscribe",
    "List-Unsubscribe-Post",
    "List-Post",
    "List-Help",
    "List-Subscribe",
    "List-Owner",
    "List-Archive",
    "X-BeenThere",
    "X-Mailman-Version",
    /* Sender tracking */
    "X-Originating-IP",
    "X-Sender-IP",
    "X-Get-Message-Sender-Via",
    "X-Originating-Email",
    "X-Authenticated-Sender",
    "X-Sender",
    "Organization",
    "X-Organization",
    "X-Country",
    "X-IP",
    /* Cloud security / filtering services */
    "X-cloud-security",
    "X-cloud-security-connect",
    "X-cloud-security-Digest",
    "X-cloud-security-disclaimer",
    "X-cloud-security-recipient",
    "X-cloud-security-sender",
    "X-cloud-security-Virusscan",
    "X-CMAE-Analysis",
    "X-CMAE-Envelope",
    "X-Greylist",
    /* CodeTwo tracking */
    "X-CodeTwo-MessageID",
    "X-CodeTwoProcessed",
    /* Service provider / hosting metadata */
    "X-AliDM-RcptTo",
    "X-Postal-MsgID",
    "X-PPE-TRUSTED",
    "X-PPP-Message-ID",
    "X-PPP-Vhost",
    "X-SECURESERVER-ACCT",
    "X-SG-EID",
    "X-RSMIdSession",
    /* Message tracking/identification */
    "X-Entity-ID",
    "X-EnvId",
    "X-Filter-ID",
    "X-MDID",
    "X-MDID-O",
    "Feedback-ID",
    "X-Forwarded-Encrypted",
    "X-Received",
    "X-Recommended-Action",
    "X-Report-Abuse-To",
    "X-Source",
    "X-Source-Args",
    "X-Source-Dir",
    /* Obsolete/rarely used RFC headers */
    "Comments",
    "Keywords",
    "Resent-From",
    "Resent-Date",
    "Resent-To",
    "Resent-Message-ID",
    "Resent-Sender",
    "Status",
    "X-Status",
    "X-UID",
    /* Post-delivery metadata */
    "Delivered-To",
    "Return-Path",
    "X-Original-To",
    /* Authentication signatures */
    "DKIM-Signature",
    "DKIM-Filter",
    "Received-SPF",
    /* Spam filtering metadata */
    "X-Spam-Checker-Version",
    "X-Spam-Status",
    "X-Spam-Flag",
    "X-Spam-Level",
    "X-Spam-Report",
    "X-Spam-Score",
    "X-Proofpoint-NotVirusScanned",
    NULL  /* sentinel */
};

#endif /* MAILHEADERCLEAN_HEADERS_H */
