#!/bin/bash

mailgetheaders() {
  local -n headers="$1"
  [[ -f "$2" ]] || return 1
  headers=()
  local -- line
  while read -r line; do
    #shellcheck disable=SC2034
    headers[${line%%:*}]="${line#*: }"
  done < <(mailheader "$2")
  return 0
}
declare -fx mailgetheaders

if [[ ${BASH_SOURCE[0]} == "$0" ]]; then
  set -euo pipefail

  declare -A Headers=()
  
  declare -- mdir_file="${1:-}"

  mdir_file=$(readlink -en -- "$mdir_file") || {
    >&2 echo "$(basename -- "$0"): File '$1' not found"
    exit 1
  }
  
  mailgetheaders Headers "$mdir_file" || { 
    declare -i err=$?
    >&2 echo "$(basename -- "$0"): Error $err in mailgetheaders"
    exit $err
  }
  Headers[file]="$mdir_file"  

  declare -p Headers
fi
 
#fin
